# Generated by Django 5.0.3 on 2024-03-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/user.svg', upload_to='profile_photos/'),
        ),
    ]
