# Generated by Django 5.0.3 on 2024-03-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_student_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
